-- Generated by db-diff.sh on 2026-06-26T11:36:07Z
-- REVIEW before applying — verify renames are RENAME/CHANGE, not DROP+ADD.

-- DropForeignKey
ALTER TABLE `vendor_invoice` DROP FOREIGN KEY `fk_vendor_invoice_vendor`;

-- AlterTable
ALTER TABLE `vendor_invoice` MODIFY `vendor_id` int NULL;

-- AddForeignKey
ALTER TABLE `vendor_invoice` ADD CONSTRAINT `fk_vendor_invoice_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendor`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
