#!/usr/bin/env bash
# =============================================================================
# Converge — DB diff (generate a forward-only delta)
# =============================================================================
# Computes the difference between the CURRENT database (DATABASE_URL) and the
# canonical prisma/sql/schema.sql (Riana's Workbench export), and writes it as a
# reviewable script to prisma/sql/migrations/<timestamp>_<name>.sql.
#
# The schema stays SQL-first: schema.sql remains the source of truth; this just
# computes the delta to bring an existing DB up to it. Prisma is used ONLY as a
# DB-vs-DB diff engine here (it does not become the schema authority).
#
# IMPORTANT: always review the generated file before applying. Diff tools render
# a column rename as DROP + ADD (data loss) — convert those to RENAME/CHANGE by
# hand. Then apply with `npm run db:apply`.
#
# Usage: ./scripts/db-diff.sh [name]
# =============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA_FILE="$ROOT_DIR/prisma/sql/schema.sql"
ENV_FILE="$ROOT_DIR/.env"
MIG_DIR="$ROOT_DIR/prisma/sql/migrations"
NAME="${1:-change}"

if [[ -z "${DATABASE_URL:-}" ]]; then
  [[ -f "$ENV_FILE" ]] || { echo "Error: DATABASE_URL not set and $ENV_FILE missing." >&2; exit 1; }
  DATABASE_URL="$(grep -E '^DATABASE_URL=' "$ENV_FILE" | tail -n1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")"
fi
[[ -n "${DATABASE_URL:-}" ]] || { echo "Error: DATABASE_URL empty." >&2; exit 1; }

urldecode() { local s="${1//+/ }"; printf '%b' "${s//%/\\x}"; }
# Parse mysql://[user[:pass]]@host[:port]/dbname[?params]. Password is OPTIONAL
# (a bare `root@localhost` has none), port defaults to 3306, query params are
# stripped, and we split on the LAST @ so a password containing @ still parses.
_REST="${DATABASE_URL#mysql://}"
_USERINFO="${_REST%@*}"
_HOSTINFO="${_REST##*@}"
DB_USER="$(urldecode "${_USERINFO%%:*}")"
if [[ "$_USERINFO" == *:* ]]; then DB_PASS="$(urldecode "${_USERINFO#*:}")"; else DB_PASS=""; fi
_HOSTPORT="${_HOSTINFO%%/*}"
DB_HOST="${_HOSTPORT%%:*}"
if [[ "$_HOSTPORT" == *:* ]]; then DB_PORT="${_HOSTPORT##*:}"; else DB_PORT="3306"; fi
DB_NAME="${_HOSTINFO#*/}"; DB_NAME="${DB_NAME%%\?*}"
[[ -n "$DB_NAME" ]] || { echo "Error: could not parse database name." >&2; exit 1; }

# mysql CLI treats "localhost" as a socket; force TCP for the forwarded port.
CLI_HOST="$DB_HOST"; [[ "$DB_HOST" == "localhost" ]] && CLI_HOST="127.0.0.1"
SHADOW_NAME="${DB_NAME}_shadow_diff"
if [[ -n "$DB_PASS" ]]; then
  SHADOW_URL="mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${SHADOW_NAME}"
else
  SHADOW_URL="mysql://${DB_USER}@${DB_HOST}:${DB_PORT}/${SHADOW_NAME}"
fi

export MYSQL_PWD="$DB_PASS"
MY() { mysql --protocol=TCP -h "$CLI_HOST" -P "$DB_PORT" -u "$DB_USER" "$@"; }

cleanup() { MY -e "DROP DATABASE IF EXISTS \`$SHADOW_NAME\`;" >/dev/null 2>&1 || true; }
trap cleanup EXIT

echo "Loading schema.sql into shadow DB ($SHADOW_NAME)..."
MY -e "DROP DATABASE IF EXISTS \`$SHADOW_NAME\`; CREATE DATABASE \`$SHADOW_NAME\` DEFAULT CHARACTER SET utf8mb4;"
MY "$SHADOW_NAME" < "$SCHEMA_FILE"

echo "Diffing $DB_NAME (current) → schema.sql ..."
DIFF="$(cd "$ROOT_DIR" && npx prisma migrate diff --from-url "$DATABASE_URL" --to-url "$SHADOW_URL" --script)"

# Detect a real change (ignore comment/blank-only output).
BODY="$(echo "$DIFF" | grep -vE '^[[:space:]]*(--|$)' || true)"
if [[ -z "$BODY" ]]; then
  echo "No schema changes — current DB already matches schema.sql."
  exit 0
fi

mkdir -p "$MIG_DIR"
OUT="$MIG_DIR/$(date +%Y%m%d%H%M%S)_${NAME}.sql"
{
  echo "-- Generated by db-diff.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "-- REVIEW before applying — verify renames are RENAME/CHANGE, not DROP+ADD."
  echo
  echo "$DIFF"
} > "$OUT"
echo
echo "Wrote delta: ${OUT#"$ROOT_DIR"/}"
echo "Review it, then run: npm run db:apply"
